INSERT INTO COURSE(ID, NAME, CREATE_DATE, LAST_UPDATE_DATE) VALUES (1000, 'Training Dogs', SYSDATE(), SYSDATE());
INSERT INTO COURSE(ID, NAME, CREATE_DATE, LAST_UPDATE_DATE) VALUES (1001, 'Training Cats', SYSDATE(), SYSDATE());
INSERT INTO COURSE(ID, NAME, CREATE_DATE, LAST_UPDATE_DATE) VALUES (1002, 'Training Rabbits', SYSDATE(), SYSDATE());
INSERT INTO COURSE(ID, NAME, CREATE_DATE, LAST_UPDATE_DATE) VALUES (1003, 'Training All pets', SYSDATE(), SYSDATE());